export const BD_LOCATIONS = [
  "Dhanmondi, Dhaka",
  "Gulshan, Dhaka",
  "Banani, Dhaka",
  "Uttara, Dhaka",
  "Mirpur, Dhaka",
  "Mohammadpur, Dhaka",
  "Rayer Bazar, Dhaka",
  "Bashundhara, Dhaka",
  "Motijheel, Dhaka",
  "Farmgate, Dhaka",
  "Tejgaon, Dhaka",
  "Khilgaon, Dhaka",
  "Mohakhali, Dhaka",
  "Baridhara, Dhaka",
  "Savar, Dhaka",
  "Narayanganj",
  "Gazipur",
  "Tangail",
  "Faridpur",
  "Madaripur",
  "Shariatpur",
  "Manikganj",
  "Munshiganj",
  "Kishoreganj",
  "Narsingdi",
  "Rajbari",
  "Comilla",
  "Brahmanbaria",
  "Noakhali",
  "Feni",
  "Lakshmipur",
  "Chandpur",
  "Sylhet",
  "Moulvibazar",
  "Habiganj",
  "Sunamganj",
  "Chattogram",
  "Cox's Bazar",
  "Rangamati",
  "Khulna",
  "Jessore",
  "Satkhira",
  "Bagerhat",
  "Kushtia",
  "Magura",
  "Narail",
  "Meherpur",
  "Chuadanga",
  "Pirojpur",
  "Barishal",
  "Patuakhali",
  "Bhola",
  "Jhalokathi",
  "Barguna",
  "Sirajganj",
  "Pabna",
  "Bogra",
  "Natore",
  "Nawabganj",
  "Joypurhat",
  "Rajshahi",
  "Naogaon",
  "Chapai Nawabganj",
  "Panchagarh",
  "Thakurgaon",
  "Kurigram",
  "Lalmonirhat",
  "Dinajpur",
  "Nilphamari",
  "Gaibandha",
  "Sherpur",
  "Mymensingh",
];

export const BD_LOCATIONS_ALL = ["All Areas", ...BD_LOCATIONS];
